### DISCUSSION TITLE
Docker containers restarting loop

### DISCUSSION THREAD

**Discussion by ddenev** [appwrite/appwrite#3275] [Q&A]
Hi,

I have Appwrite 0.14.2 installed on Docker for Windows (under WSL2). My PC has 32GB of RAM.

Several days ago, while working on my project with docker running, suddenly my browser and some other apps started crashing due to not enough memory. After checking I discovered that WSL2 is giving 80% of my memory to Docker.

So I added this to my .wslconfig file:
```
[wsl2]
memory=16GB
```
and rebooted.

After a while some of the Appwrite containers entered a restarting loop, so I thought that maybe redis needs flushing. So I flushed my redis and for some time Appwrite was working (several hours) but then again containers started restarting.

Aren't 16GB enough for Appwrite?
What do I need to configure to make it run on 16GB or 8GB of WSL RAM without restarting all the time?

**Comment by lucasbstn** [comment]
Facing exactly same issue here. Running Appwrite 0.14.2 on Digital Ocean droplet with 4gb ram.

**Comment by stnguyen90** [comment]
What's in your mariadb logs?

**Reply by ddenev** [reply]
> What's in your mariadb logs?

Nothing interesting, really - only notices and some warnings that have no relation to the issue. MariaDB is running OK, I think it's Redis that causes the restarting.

**Reply by stnguyen90** [reply]
What's the output of the Redis logs?

**Comment by ddenev** [comment]
Checked the redis logs and there was also nothing that would indicate a problem, just info that Redis is restarting and also this one, which I am not sure that it relates:
```
1:M 25 May 2022 06:19:16.524 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
```

Actually, what I did is add these to my `docker-compose.yml` file:
```
redis:
    image: redis:6.2-alpine
    container_name: appwrite-redis
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-redis:/data:rw
    # -------------------------------- ADD THIS
    deploy:    
      resources:
        limits:
          memory: 4096M
    command: >
      --maxmemory 2048mb
      --maxmemory-policy allkeys-lru
    # -------------------------------- ADD THIS
```
and now I don't have restarts anymore. will continue watching it anyways.

It's strange why Appwrite's Redis is left "unattended", i.e. not configured to be mindful of the available memory. Maybe the above configuration should go into the default install and documentation?
