### DISCUSSION TITLE
Appwrite and another container managed by Traefik.

### DISCUSSION THREAD

**Discussion by fvdf** [appwrite/appwrite#5471] [Q&A]
Hello everyone. I am setting up a server on my Raspberry Pi that allows me to access Appwrite from a domain 'appwrite.domaine.fr', and everything is working.

The problem you're facing today is that you want to use Traefik to also host a small website with nginx ('site.domaine.fr'), and in the future, you'd also like to have a Nextcloud instance ('cloud.domaine.fr').

Today I manage to have my nginx site managed by Traefik with the code below, can you tell me how to adapt my Docker Compose file to make Appwrite accessible from 'appwrite.domaine.fr'?

```
version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging>
      - "--certificatesresolvers.myresolver.acme.email=fvdf@domaine.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nginx:
    image: "nginx:latest"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`site.domaine.fr`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=myresolver"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
```

I had seen that there was a project for Appwrite Lite underway which seems to be on hold or even abandoned. Do you have any information about it? (I'm wondering if it could be the solution). 

I'm sorry for my poor English. Thank you in advance to anyone who is willing to help. I'm waiting for your response and I'm available for any questions.
