### ISSUE TITLE
🐛 Bug Report: The current project has exceeded the maximum number of users. Please check your user limit in the Appwrite console.

### ISSUE THREAD

**Issue by wolf27w** [appwrite/appwrite#10041]
### 👟 Reproduction steps

After registering the first user, when registering the second user, it prompts: The current project has exceeded the maximum number of users. Please check your user limit in the Appwrite console.

### 👍 Expected behavior

Registration successful

### 👎 Actual Behavior

Registration failed, prompt: The current project has exceeded the maximum number of users. Please check your user limit in the Appwrite console.

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Kubernetes environment, version 1.26.2

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by wolf27w** [comment]
![Image](https://github.com/user-attachments/assets/288f05cf-d8af-4653-9a87-4c8de389c7be)

```
data:
  _APP_ENV: "production"
  _APP_LOCALE: "en"
  _APP_OPTIONS_ABUSE: "enabled"
  _APP_OPTIONS_FORCE_HTTPS: "disabled"
  _APP_OPTIONS_FUNCTIONS_FORCE_HTTPS: "disabled"
  _APP_OPTIONS_ROUTER_PROTECTION: "disabled"
  _APP_DOMAIN: "appwrite.example.com"
  _APP_DOMAIN_FUNCTIONS: "functions.example.com"
  _APP_DOMAIN_TARGET: "appwrite.example.com"
  _APP_CONSOLE_WHITELIST_ROOT: "enabled"
  _APP_CONSOLE_WHITELIST_EMAILS: ""
  _APP_CONSOLE_WHITELIST_IPS: ""
  _APP_SYSTEM_EMAIL_NAME: "Appwrite"
  _APP_SYSTEM_EMAIL_ADDRESS: "team@appwrite.io"
  _APP_SYSTEM_RESPONSE_FORMAT: ""
  _APP_SYSTEM_SECURITY_EMAIL_ADDRESS: "certs@appwrite.io"
  _APP_USAGE_STATS: "enabled"
  _APP_LOGGING_PROVIDER: ""
  _APP_LOGGING_CONFIG: ""
  _APP_USAGE_AGGREGATION_INTERVAL: "30"
  _APP_USAGE_TIMESERIES_INTERVAL: "30"
  _APP_USAGE_DATABASE_INTERVAL: "900"
  _APP_WORKER_PER_CORE: "6"
  _APP_REDIS_HOST: "appwrite-redis"
  _APP_REDIS_PORT: "6379"
  _APP_DB_HOST: "appwrite-mariadb-master"
  _APP_DB_PORT: "3306"
  _APP_DB_SCHEMA: "appwrite"
  _APP_DB_USER: "root"
  _APP_INFLUXDB_HOST: "appwrite-influxdb"
  _APP_INFLUXDB_PORT: "8086"
  _APP_STATSD_HOST: "appwrite-telegraf"
  _APP_STATSD_PORT: "8125"
  _APP_SMTP_HOST: ""
  _APP_SMTP_PORT: ""
  _APP_SMTP_SECURE: ""
  _APP_SMTP_USERNAME: ""
  _APP_SMS_PROVIDER: ""
  _APP_SMS_FROM: ""
  _APP_STORAGE_LIMIT: "30000000"
  _APP_STORAGE_PREVIEW_LIMIT: "20000000"
  _APP_STORAGE_ANTIVIRUS: "disabled"
  _APP_STORAGE_ANTIVIRUS_HOST: "clamav"
  _APP_STORAGE_ANTIVIRUS_PORT: "3310"
  _APP_STORAGE_DEVICE: "s3"
  _APP_STORAGE_S3_ACCESS_KEY: ""
  _APP_STORAGE_S3_REGION: "us-east-1"
  _APP_STORAGE_S3_BUCKET: ""
  _APP_STORAGE_DO_SPACES_ACCESS_KEY: ""
  _APP_STORAGE_DO_SPACES_REGION: "us-east-1"
  _APP_STORAGE_DO_SPACES_BUCKET: ""
  _APP_STORAGE_BACKBLAZE_ACCESS_KEY: ""
  _APP_STORAGE_BACKBLAZE_REGION: "us-west-004"
  _APP_STORAGE_BACKBLAZE_BUCKET: ""
  _APP_STORAGE_LINODE_ACCESS_KEY: ""
  _APP_STORAGE_LINODE_REGION: "eu-central-1"
  _APP_STORAGE_LINODE_BUCKET: ""
  _APP_STORAGE_WASABI_ACCESS_KEY: ""
  _APP_STORAGE_WASABI_REGION: "eu-central-1"
  _APP_STORAGE_WASABI_BUCKET: ""
  _APP_FUNCTIONS_SIZE_LIMIT: "30000000"
  _APP_FUNCTIONS_TIMEOUT: "900"
  _APP_FUNCTIONS_BUILD_TIMEOUT: "900"
  _APP_FUNCTIONS_CONTAINERS: "10"
  _APP_FUNCTIONS_CPUS: "0"
  _APP_FUNCTIONS_MEMORY: "0"
  _APP_FUNCTIONS_MEMORY_SWAP: "0"
  _APP_FUNCTIONS_RUNTIMES: "php-8.1,dart-2.18,deno-1.24,node-18.0,python-3.10,ruby-3.1,cpp-17,dotnet-6.0"
  _APP_EXECUTOR_HOST: "https://docker.swarm.opr.proxy/v1"
  _APP_EXECUTOR_RUNTIME_NETWORK: "appwrite_runtimes"
  _APP_FUNCTIONS_ENVS: "php-8.1,dart-2.18,deno-1.24,node-18.0,python-3.10,ruby-3.1,cpp-17,dotnet-6.0"
  _APP_FUNCTIONS_INACTIVE_THRESHOLD: "60"
  DOCKERHUB_PULL_USERNAME: ""
  DOCKERHUB_PULL_EMAIL: ""
  OPEN_RUNTIMES_NETWORK: "appwrite_runtimes"
  _APP_FUNCTIONS_RUNTIMES_NETWORK: "runtimes"
  _APP_DOCKER_HUB_USERNAME: ""
  _APP_FUNCTIONS_MAINTENANCE_INTERVAL: "3600"
  _APP_VCS_GITHUB_APP_NAME: ""
  _APP_VCS_GITHUB_APP_ID: ""
  _APP_VCS_GITHUB_CLIENT_ID: ""
  _APP_MAINTENANCE_INTERVAL: "86400"
  _APP_MAINTENANCE_RETENTION_CACHE: "2592000"
  _APP_MAINTENANCE_RETENTION_EXECUTION: "1209600"
  _APP_MAINTENANCE_RETENTION_AUDIT: "1209600"
  _APP_MAINTENANCE_RETENTION_ABUSE: "86400"
  _APP_MAINTENANCE_RETENTION_USAGE_HOURLY: "8640000"
  _APP_MAINTENANCE_RETENTION_SCHEDULES: "86400"
  _APP_GRAPHQL_MAX_BATCH_SIZE: "10"
  _APP_GRAPHQL_MAX_COMPLEXITY: "250"
  _APP_GRAPHQL_MAX_DEPTH: "3"
  _APP_MIGRATIONS_FIREBASE_CLIENT_ID: ""
  _APP_REALTIME_ENABLED: "true"
```

This is my environment variable
