### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by rlee1990** [appwrite/appwrite#1377]
I get an error that says it failed to add the requested platform when using this branch.
Switching back to 0.9 allows me to add them.
When using the Flutter version I cannot sign in or sign up users It gives an exception that I cannot get to even display using a try catch block.
```
appwrite:
    git:
      url: https://github.com/appwrite/sdk-for-flutter
      ref: feat-realtime
```

---
Appwrite Version: dev.146
