### ISSUE TITLE
Allow parallel execution of functions

### ISSUE THREAD

**Issue by rdmchr** [appwrite/appwrite#1425]
## 🚀 Feature

I believe that it would be nice if one function could run multiple times at the same time.

## Have you spent some time to check if this issue has been raised before?

Yes.

### Have you read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/master/CODE_OF_CONDUCT.md)?

Yes.

## Pitch

Let's say I'm running a function that does some OCR on all uploaded images. One run of the function usually takes 25 seconds. In my use case, users will be able to scan some handwritten stuff and the text will be saved into a database. Since I expect users to submit images in batches of let's say 10. This means that a user will have to wait over 4 minutes for their papers to get scanned.
Since my server can handle 4 parallel executions this could be reduced to about 1 minute.

I'm not sure about the implementation but from the looks of it you would definitely need to change the naming scheme of function containers.

**Comment by eldadfux** [comment]
@rdmchr you can get more parallel executions by adding more functions worker containers in your docker stack. For example:

```yaml
...
appwrite-worker-functions-1:
    entrypoint: worker-functions
    container_name: appwrite-worker-functions
    build:
      context: .
    networks:
      - appwrite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-functions:/storage/functions:rw
      - /tmp:/tmp:rw
      - ./app:/usr/src/code/app
      - ./src:/usr/src/code/src
    depends_on:
      - redis
      - mariadb
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_FUNCTIONS_TIMEOUT
      - _APP_FUNCTIONS_CONTAINERS
      - _APP_FUNCTIONS_RUNTIMES
      - _APP_FUNCTIONS_CPUS
      - _APP_FUNCTIONS_MEMORY
      - _APP_FUNCTIONS_MEMORY_SWAP
      - _APP_USAGE_STATS
      - DOCKERHUB_PULL_USERNAME
      - DOCKERHUB_PULL_PASSWORD
 
appwrite-worker-functions-2:
    entrypoint: worker-functions
    container_name: appwrite-worker-functions
    build:
      context: .
    networks:
      - appwrite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-functions:/storage/functions:rw
      - /tmp:/tmp:rw
      - ./app:/usr/src/code/app
      - ./src:/usr/src/code/src
    depends_on:
      - redis
      - mariadb
    environment:
      - _APP_ENV
      - _APP_OPENSSL_KEY_V1
      - _APP_REDIS_HOST
      - _APP_REDIS_PORT
      - _APP_REDIS_USER
      - _APP_REDIS_PASS
      - _APP_DB_HOST
      - _APP_DB_PORT
      - _APP_DB_SCHEMA
      - _APP_DB_USER
      - _APP_DB_PASS
      - _APP_FUNCTIONS_TIMEOUT
      - _APP_FUNCTIONS_CONTAINERS
      - _APP_FUNCTIONS_RUNTIMES
      - _APP_FUNCTIONS_CPUS
      - _APP_FUNCTIONS_MEMORY
      - _APP_FUNCTIONS_MEMORY_SWAP
      - _APP_USAGE_STATS
      - DOCKERHUB_PULL_USERNAME
      - DOCKERHUB_PULL_PASSWORD
 ...
```

The upcoming update to functions will introduce sync execution where you could get the execution response immediately. Using this model, scaling will behave more similarly to the API. It will use multiple co-routines for parallel executions.
