### ISSUE TITLE
🚀 Feature: Own images behind traefik

### ISSUE THREAD

**Issue by reyesmfabian** [appwrite/appwrite#2753]
Hello, 

I'm not a Docker expert, but I've been trying to learn a lot. I have a question.

I have some personal servers working with nginx-proxy to serve a backend and frontend with the same server with letsencrypt https.

Is it possible to do the same with Appwrite? I.e. serve appwrite and other images with full https with letsencrypt? 

this is an example of my docker-compose for my personal sites.

```
version: '3'

services:
  image_name:
    image: myimage
    container_name: myimage
    restart: always
    environment:
      - VIRTUAL_HOST=mydomain.com
      - LETSENCRYPT_HOST=mydomain.com
      - LETSENCRYPT_EMAIL=mail@mydomain.com
    volumes:
      - ./myimage
    expose:
      - "80"
    depends_on:
      - nginx-proxy
      - letsencrypt

  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: nginxproxy/acme-companion:2.0.2
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes: 
  certs:
  html:
  vhostd:
  dhparam:
  acme:
```
