### ISSUE TITLE
🐛 Bug Report: Support public dev domains

### ISSUE THREAD

**Issue by zaclimon** [appwrite/appwrite#2754]
### 👟 Reproduction steps

I installed appwrite and configured my project so it would point to my personal domain which is `isaacpateau.dev`.

However, when I try to reach it, I notice that a self-signed certificate has been issued instead of using one from Let's Encrypt. Upon [reading the documentation](https://appwrite.io/docs/environment-variables), on the`_APP_DOMAIN` variable, I see that when a "public" domain is used, Appwrite will generate a valid certificate. With that said, when a "dev" domain is used, it will generate a self-signed one. Though "dev" domains are also public.

### 👍 Expected behavior

Being able to reach my appwrite instance with my "dev" domain.

### 👎 Actual Behavior

I get an error from my web browser that I can't access the website because it is using an self-signed certificate.

Furthermore, when trying to validate my custom domain, it is not working. I receive a "Failed to verify domain" as shown below.

![image](https://user-images.githubusercontent.com/1891861/152700720-35ccde1a-b3b3-40fc-93ca-65390118b636.png)

### 🎲 Appwrite version

Version 0.12.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Since I'm also using Netlify as the DNS manager, it forces HTTPS and HSTS on its domains so I'm not able to access my server through them because of the self-signed certificate. I'm using the server's IP address to access the instance which works, but is only a workaround at the moment.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I don't think there's anything wrong with .dev domains. The self signed traefik certificate is there by default and a valid certificate should be generated automatically for the domain specified in your .env var. You don't need to add a custom domain in your project settings. Please read through this to troubleshoot: https://appwrite.io/docs/certificates. if you're still having problems, join us on discord for additional support.

**Comment by eldadfux** [comment]
> I don't think there's anything wrong with .dev domains. The self signed traefik certificate is there by default and a valid certificate should be generated automatically for the domain specified in your .env var. You don't need to add a custom domain in your project settings. Please read through this to troubleshoot: https://appwrite.io/docs/certificates. if you're still having problems, join us on discord for additional support.

I was looking through the source code and haven't found anything specific for `.dev` domains, I suspect the docs might be wrong.

**Comment by zaclimon** [comment]
For the time being, I tried using another domain which is ".com" and it worked. But then this might be related to my DNS provider. I tried connecting again and I got blocked because of HSTS I'll leave two screenshots here. One with the error from Edge.

<img src="https://user-images.githubusercontent.com/1891861/153296853-6b1370f1-8ba0-4638-8a98-bb91c17769c8.png" width=50% height=50%>

Another showing that the self-signed certificate is used instead of the Let's Encrypt one.

<img src="https://user-images.githubusercontent.com/1891861/153297036-b3e00943-be33-40ee-b937-45677d156299.png" width=50% height=50%>

We can still discuss this over on Discord to fix this and post a solution there to avoid cluttering.

**Comment by zaclimon** [comment]
In the end I managed to fix my problem. The issue in the end was that my ISP (Bell) blocks port 80 on residential connections. This would cause the ACME HTTP challenge to fail and thus, not retrieve the certificate. (Looked at the logs from `appwrite-worker-certificates`) for more details.

I fixed this by using the TLS challenge instead and modifying a little bit the `docker-compose.yml`, based on [Traefik's documentation](https://doc.traefik.io/traefik/v2.0/user-guides/docker-compose/acme-tls/).

More precisely:

- I added most config items for Traefik (minus the debug and the staging CA server line). I also created a temporary volume for storing the certificates. Probably it would be better to save it in `appwrite-certificate` volume instead.
- In the `appwrite` container's https section, in addition to add the certsresolver definition, I also added a host rule which points to my domain.

Below is a example of the `docker-compose.yml` I used in the end (I only kept the most necessary parts):

```yml
version: '3'

services:
  traefik:
    image: traefik:2.5
    container_name: appwrite-traefik
    command:
      - --providers.file.directory=/storage/config
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`,`appwrite`)
      - --entrypoints.appwrite_web.address=:80
      - --entrypoints.appwrite_websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=your@email.com
      - --certificatesresolvers.myresolver.acme.storage=/storage/letsencrypt/acme.json
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-config:/storage/config:ro
      - appwrite-certificates:/storage/certificates:ro
      - appwrite-letsencrypt:/storage/letsencrypt
    depends_on:
      - appwrite
    networks:
      - gateway
      - appwrite

  appwrite:
    image: appwrite/appwrite:0.12.1
    container_name: appwrite
    restart: unless-stopped
    networks:
      - appwrite
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=appwrite
      - traefik.docker.network=appwrite
      - traefik.http.services.appwrite_api.loadbalancer.server.port=80
      #http
      - traefik.http.routers.appwrite_api_http.entrypoints=appwrite_web
      - traefik.http.routers.appwrite_api_http.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite_api_http.service=appwrite_api
      # https
      - traefik.http.routers.appwrite_api_https.entrypoints=appwrite_websecure
      - traefik.http.routers.appwrite_api_https.rule=(Host(`your.domain.com`) || PathPrefix(`/`))
      - traefik.http.routers.appwrite_api_https.service=appwrite_api
      - traefik.http.routers.appwrite_api_https.tls=true
      - traefik.http.routers.appwrite_api_https.tls.certresolver=myresolver

volumes:
  appwrite-letsencrypt:
```

Since the problem isn't related to the handling of ".dev" domains per-se, it will be closed.
