### ISSUE TITLE
🐛 Bug Report: Appwrite dumps when creating metadata table after fresh install

### ISSUE THREAD

**Issue by vijedich** [appwrite/appwrite#3095]
### 👟 Reproduction steps

Use appwrite/install to create a compose file.
Start it,
Look at the logs for the appwrite container.

### 👍 Expected behavior

Start up and let me be happy about my freshly installed appwrite stack.

### 👎 Actual Behavior

No Start up and no one is happy about a freshly install appwrite stack.

Log:
Worker 1 started successfully
[Setup] - Server database init started...
[Setup] - Creating metadata table: appwrite...

Fatal error: Uncaught PDOException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DISTINCT _permission)

                    FROM `appwrite`.`_console__metadata_pe' at line 4 in @swoole-src/library/core/Database/PDOStatementProxy.php:64

Stack trace:
#0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(372): Swoole\Database\PDOStatementProxy->__call('execute', Array)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(772): Utopia\Database\Adapter\MariaDB->getDocument('_metadata', 'audit')
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(379): Utopia\Database\Database->getDocument(Object(Utopia\Database\Document), 'audit')
#3 /usr/src/code/app/http.php(104): Utopia\Database\Database->getCollection('audit')

}
  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64

[2022-04-14 09:25:29 #1.2]	ERROR	php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught PDOException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DISTINCT _permission)

                    FROM `appwrite`.`_console__metadata_pe' at line 4 in @swoole-src/library/core/Database/PDOStatementProxy.php:64

Stack trace:
#0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(372): Swoole\Database\PDOStatementProxy->__call('execute', Array)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(772): Utopia\Database\Adapter\MariaDB->getDocument('_metadata', 'audit')
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(379): Utopia\Database\Database->getDocument(Object(Utopia\Database\Document), 'audit')
#3 /usr/src/code/app/http.php(104): Utopia\Database\Database->getCollection('audit')
}

  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64

### 🎲 Appwrite version

Version 0.13.x

### 💻 Operating system

Linux

### 🧱 Your Environment

No, just a minimal debian 11 installation.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
@vijedich  thanks for raising this..

By any chance 
1) Do you have another instance of MariaDB running that could be conflicting with the default service ?
2) Did you previously have Appwrite installed ? and did you now change ( or upgrade ) your Appwrite version ? 

To me it looks like an issue of a corrupt volume..
You can try and re-deploy your stack with 

```
docker-compose down -v --remove-orphans
docker-compose up -d --build --force-recreate
```

**Comment by vijedich** [comment]
Hi @christyjacob4, I tried stopping, starting again, removing the complete stack etc.
I had the sam issues with all 13.x version.
When I tried 12.4 it worked fine, but everything from 13.0 to 13.4 had the same issue.

**Comment by vijedich** [comment]
Oh, and I created the server I use specifically for appwrite so there is only portainer running on it.

**Comment by stnguyen90** [comment]
> Hi @christyjacob4, I tried stopping, starting again, removing the complete stack etc.
> I had the sam issues with all 13.x version.
> When I tried 12.4 it worked fine, but everything from 13.0 to 13.4 had the same issue.

You said you had version 0.12.4 on the server? Did you then install 0.13 on the same server? Your 0.13 instance may be using the 0.12 database which won't work without migration.

**Comment by vijedich** [comment]
Hi @christyjacob4 I initial started with 13.4 but got the dump. Then I tried to move back version by version. And with 12.4 it finally started up.

**Comment by khashashin** [comment]
I've same problem. MariaDB is hosted externally.

![image](https://user-images.githubusercontent.com/17837758/178129924-dbb2bb4a-ff19-4ebf-80fa-72a99519b842.png)
```
[Static Files] Loadded 135 files
Worker 1 started successfully
Worker 3 started successfully
Worker 4 started successfully
Worker 2 started successfully
[Setup] - Server database init started...
[Setup] - Creating metadata table: appwrite...

Fatal error: Uncaught PDOException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DISTINCT _permission)
                    FROM `appwrite`.`_console__metadata...' at line 4 in @swoole-src/library/core/Database/PDOStatementProxy.php:64
Stack trace:
#0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(431): Swoole\Database\PDOStatementProxy->__call('execute', Array)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1065): Utopia\Database\Adapter\MariaDB->getDocument('_metadata', 'audit')
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(391): Utopia\Database\Database->getDocument(Object(Utopia\Database\Document), 'audit')
#3 /usr/src/code/app/http.php(104): Utopia\Database\Database->getCollection('audit')
#4 {main}
  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64
[2022-07-10 03:09:42 #1.4]      ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught PDOException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DISTINCT _permission)
                    FROM `appwrite`.`_console__metadata...' at line 4 in @swoole-src/library/core/Database/PDOStatementProxy.php:64
Stack trace:
#0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(431): Swoole\Database\PDOStatementProxy->__call('execute', Array)
#1 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1065): Utopia\Database\Adapter\MariaDB->getDocument('_metadata', 'audit')
#2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(391): Utopia\Database\Database->getDocument(Object(Utopia\Database\Document), 'audit')
#3 /usr/src/code/app/http.php(104): Utopia\Database\Database->getCollection('audit')
#4 {main}
  thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64
```

Also note that I've commented out the env variable:
```
#_APP_DB_ROOT_PASS
```

It would be nice if we could define admin (root) user of MariaDB Instance. Maybe something: `_APP_DB_ROOT_USERNAME`. In my case I've disabled root access and use another custom user with almost same privileges.

However Appwrite has created two Tables:
![image](https://user-images.githubusercontent.com/17837758/178130013-99e4d2c0-b0ee-4594-905c-cdc7c32b6e64.png)

**Comment by stnguyen90** [comment]
> In my case I've disabled root access and use another custom user with almost same privileges.

@khashashin, are you using that use for `_APP_DB_USER` and `_APP_DB_PASS`? Also, you're using MariaDB and not MySQL, right? What version of MariaDB are you running?

**Comment by khashashin** [comment]
> @khashashin, are you using that use for `_APP_DB_USER` and `_APP_DB_PASS`? Also, you're using MariaDB and not MySQL, right? What version of MariaDB are you running?

Yeah, I've `_APP_DB_USER=appwrite`,  `_APP_DB_PASS=xxxxxxx`,  `_APP_DB_NAME=appwrite` and `_APP_DB_HOST=external.host.com` but I did not set `_APP_DB_ROOT_PASS`

**Comment by stnguyen90** [comment]
@khashashin what version of Appwrite are you on?

**Comment by khashashin** [comment]
> @khashashin what version of Appwrite are you on?

I'm on `image: appwrite/appwrite:0.15.1`

**Comment by stnguyen90** [comment]
@khashashin, can you check what's in your 2 tables?

**Comment by khashashin** [comment]
> @khashashin, can you check what's in your 2 tables?

They are empty, both
![image](https://user-images.githubusercontent.com/17837758/178162610-f36d5d50-884e-4cd7-8cb1-bdc8cad5002e.png)

![image](https://user-images.githubusercontent.com/17837758/178162626-056e5e09-5bc9-415a-aa2f-8dde4c12a800.png)

**Comment by khashashin** [comment]
Is `_APP_DB_ROOT_PASS` variable required?

**Comment by stnguyen90** [comment]
> Is `_APP_DB_ROOT_PASS` variable required? 

Nope. In the docker-compose.yml file to you can see it's not passed into any other container. It's mostly required because a root password is required to create the mariadb container.

> They are empty, both ![image](https://user-images.githubusercontent.com/17837758/178162610-f36d5d50-884e-4cd7-8cb1-bdc8cad5002e.png)
> 
> ![image](https://user-images.githubusercontent.com/17837758/178162626-056e5e09-5bc9-415a-aa2f-8dde4c12a800.png)

Can you confirm your `appwrite` user has write access to those 2 tables?

**Comment by khashashin** [comment]
`appwrite` user has the following database privileges (Note this checkboxes show the privileges of `appwrite` user to `appwrite` Database: 
![image](https://user-images.githubusercontent.com/17837758/178604380-763317d7-36e2-4139-b518-afc2d8b05e71.png)

`appwrite` user does not have any Global privilege:
![image](https://user-images.githubusercontent.com/17837758/178604636-82382e62-c5a6-4060-a4ec-49a323e97813.png)

**Comment by khashashin** [comment]
And, yes I can write in to the tables
![image](https://user-images.githubusercontent.com/17837758/178605571-e55a17ac-b129-4d6d-9d3a-de3dbe5ddb4f.png)

**Comment by stnguyen90** [comment]
Thanks. would you please check your appwrite docker container logs to see if there are any errors in there? The appwrite container should have created the records on startup.

**Comment by khashashin** [comment]
> Thanks. would you please check your appwrite docker container logs to see if there are any errors in there? The appwrite container should have created the records on startup.

```
appwrite                        | [Static Files] Loadded 135 files
appwrite                        | Worker 1 started successfully
appwrite                        | Worker 2 started successfully
appwrite                        | Worker 3 started successfully
appwrite                        | Worker 4 started successfully
appwrite                        | [Setup] - Server database init started...
appwrite                        | [Setup] - Creating metadata table: appwrite...
appwrite                        |
appwrite                        | Fatal error: Uncaught PDOException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DISTINCT _permission)
appwrite                        |                     FROM `appwrite`.`_console__metadata...' at line 4 in @swoole-src/library/core/Database/PDOStatementProxy.php:64
appwrite                        | Stack trace:
appwrite                        | #0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(431): Swoole\Database\PDOStatementProxy->__call('execute', Array)
appwrite                        | #1 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1065): Utopia\Database\Adapter\MariaDB->getDocument('_metadata', 'audit')
appwrite                        | #2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(391): Utopia\Database\Database->getDocument(Object(Utopia\Database\Document), 'audit')
appwrite                        | #3 /usr/src/code/app/http.php(104): Utopia\Database\Database->getCollection('audit')
appwrite                        | #4 {main}
appwrite                        |   thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64
appwrite                        | [2022-07-13 12:27:36 #1.4]    ERROR   php_swoole_server_rshutdown() (ERRNO 503): Fatal error: Uncaught PDOException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DISTINCT _permission)
appwrite                        |                     FROM `appwrite`.`_console__metadata...' at line 4 in @swoole-src/library/core/Database/PDOStatementProxy.php:64
appwrite                        | Stack trace:
appwrite                        | #0 /usr/src/code/vendor/utopia-php/database/src/Database/Adapter/MariaDB.php(431): Swoole\Database\PDOStatementProxy->__call('execute', Array)
appwrite                        | #1 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(1065): Utopia\Database\Adapter\MariaDB->getDocument('_metadata', 'audit')
appwrite                        | #2 /usr/src/code/vendor/utopia-php/database/src/Database/Database.php(391): Utopia\Database\Database->getDocument(Object(Utopia\Database\Document), 'audit')
appwrite                        | #3 /usr/src/code/app/http.php(104): Utopia\Database\Database->getCollection('audit')
appwrite                        | #4 {main}
appwrite                        |   thrown in @swoole-src/library/core/Database/PDOStatementProxy.php on line 64
```

In case it's relevant, here's my current docker-compose content:

```
version: '3'

services:
  appwrite:
    image: appwrite/appwrite:0.15.1
    container_name: appwrite
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.appwrite.loadBalancer.server.port=80"
      - "traefik.http.routers.appwrite.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.appwrite.entrypoints=web-secure"
      - "traefik.http.routers.appwrite.rule=Host(`example.com`)"
    env_file: .env
    #entrypoint:
    #  - install
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-functions:/storage/functions:rw
    depends_on:
      - redis
        #- mariadb
      - influxdb
    networks:
      - appwrite
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-realtime:
    image: appwrite/appwrite:0.15.1
    entrypoint: realtime
    container_name: appwrite-realtime
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.appwrite_realtime.loadBalancer.server.port=80"
      - "traefik.http.routers.appwrite_realtime.entrypoints=web-secure"
      - "traefik.http.routers.appwrite_realtime.rule=(Host(`example.com`) && PathPrefix(`/v1/realtime`))"
      - "traefik.http.routers.appwrite_realtime.tls.certresolver=letsEncrypt"
    networks:
      - appwrite
    depends_on:
      #- mariadb
      - redis
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-audits:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-audits
    container_name: appwrite-worker-audits
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
        #- mariadb
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-webhooks:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-webhooks
    container_name: appwrite-worker-webhooks
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
        #- mariadb
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-deletes:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-deletes
    container_name: appwrite-worker-deletes
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
        #- mariadb
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-builds:/storage/builds:rw
      - appwrite-certificates:/storage/certificates:rw
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'


  appwrite-worker-databases:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-databases
    container_name: appwrite-worker-databases
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
        #- mariadb
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-builds:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-builds
    container_name: appwrite-worker-builds
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
        #- mariadb
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-certificates:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-certificates
    container_name: appwrite-worker-certificates
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
        #- mariadb
    volumes:
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-functions:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-functions
    container_name: appwrite-worker-functions
    restart: unless-stopped
    networks:
      - appwrite
    #link:
        #- appwrite-executor
    depends_on:
      - redis
        #- mariadb
      - appwrite-executor
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-executor:
    image: appwrite/appwrite:0.15.1
    entrypoint: executor
    container_name: appwrite-executor
    restart: unless-stopped
    stop_signal: SIGINT
    networks:
      appwrite:
      runtimes:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-functions:/storage/functions:rw
      - appwrite-builds:/storage/builds:rw
      - /tmp:/tmp:rw
    depends_on:
      - redis
        #- mariadb
      - appwrite
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-mails:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-mails
    container_name: appwrite-worker-mails
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-messaging:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-messaging
    container_name: appwrite-worker-messaging
    networks:
      - appwrite
    depends_on:
      - redis
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-maintenance:
    image: appwrite/appwrite:0.15.1
    entrypoint: maintenance
    container_name: appwrite-maintenance
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-usage:
    image: appwrite/appwrite:0.15.1
    entrypoint: usage
    container_name: appwrite-usage
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - influxdb
        #- mariadb
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-schedule:
    image: appwrite/appwrite:0.15.1
    entrypoint: schedule
    container_name: appwrite-schedule
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'


  redis:
    image: redis:6.2-alpine
    container_name: appwrite-redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory            512mb
      --maxmemory-policy     allkeys-lru
      --maxmemory-samples    5
    networks:
      - appwrite
    volumes:
      - appwrite-redis:/data:rw
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

        #mariadb:
        #image: mariadb:10.7
        #    container_name: appwrite-mariadb
        #    restart: unless-stopped
        #    environment:
        #      - MYSQL_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
        #      - MYSQL_USER=${_APP_DB_USER}
        #      - MYSQL_DATABASE=${_APP_DB_SCHEMA}
        #      - MYSQL_PASSWORD=${_APP_DB_PASS}
        #    networks:
        #      - appwrite
        #    volumes:
        #      - appwrite-mariadb:/var/lib/mysql:rw
        #    command: 'mysqld --innodb-flush-method=fsync'
        #    logging:
        #      driver: 'json-file'
        #      options:
        #        max-file: '5'
        #        max-size: '10m'

  influxdb:
    image: appwrite/influxdb:1.5.0
    container_name: appwrite-influxdb
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-influxdb:/var/lib/influxdb:rw
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  telegraf:
    image: appwrite/telegraf:1.4.0
    container_name: appwrite-telegraf
    restart: unless-stopped
    networks:
      - appwrite
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

networks:
  gateway:
  appwrite:
    external: true
  runtimes:

volumes:
  #appwrite-mariadb:
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
  appwrite-certificates:
  appwrite-functions:
  appwrite-builds:
  appwrite-influxdb:
  appwrite-config:
  appwrite-executor:
```
