### ISSUE TITLE
🐛 Bug Report: Fresh appwrite docker-compose installation. 

### ISSUE THREAD

**Issue by khashashin** [appwrite/appwrite#3496]
### 👟 Reproduction steps

Install appwrite using following docker-compose:

```
# docker-compose.yml

version: '3'

services:
  appwrite:
    image: appwrite/appwrite:0.15.1
    container_name: appwrite
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.appwrite.loadBalancer.server.port=80"
      - "traefik.http.routers.appwrite.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.appwrite.entrypoints=web-secure"
      - "traefik.http.routers.appwrite.rule=Host(`yourdomain.com`)"
    env_file: .env
    #entrypoint:
    #  - install
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-functions:/storage/functions:rw
    depends_on:
      - redis
      - mariadb
      - influxdb
    networks:
      - database
      - web

  influxdb:
    image: appwrite/influxdb:1.5.0
    container_name: appwrite-influxdb
    restart: unless-stopped
    networks:
      - database
    volumes:
      - appwrite-influxdb:/var/lib/influxdb:rw

  redis:
    image: redis:6.2-alpine
    container_name: appwrite-redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory            512mb
      --maxmemory-policy     allkeys-lru
      --maxmemory-samples    5
    networks:
      - database
    volumes:
      - appwrite-redis:/data:rw

  mariadb:
    image: mariadb:10.7
    container_name: appwrite-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
      - MYSQL_USER=${_APP_DB_USER}
      - MYSQL_DATABASE=${_APP_DB_SCHEMA}
      - MYSQL_PASSWORD=${_APP_DB_PASS}
    networks:
      - database
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    command: 'mysqld --innodb-flush-method=fsync'

networks:
  database:
    external: false
  web:
    external: true

volumes:
  appwrite-redis:
  appwrite-influxdb:
  appwrite-mariadb:
  appwrite-uploads:
  appwrite-cache:
  appwrite-config:
  appwrite-certificates:
  appwrite-functions:
```

run migrations

```
docker-compose exec appwrite migrate
```

### 👍 Expected behavior

Create project without errors

### 👎 Actual Behavior

Creating new Project through the web-interface produces following error:

```
{"message":"Error: Table 'appwrite_db._2__metadata' doesn't exist","code":500,"file":"@swoole-src\/library\/core\/Database\/PDOStatementProxy.php","line":64,"trace":[{"file":"\/usr\/src\/code\/vendor\/utopia-php\/database\/src\/Database\/Adapter\/MariaDB.php","line":431,"function":"__call","class":"Swoole\\Database\\PDOStatementProxy","type":"->","args":["execute",[]]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/database\/src\/Database\/Database.php","line":1065,"function":"getDocument","class":"Utopia\\Database\\Adapter\\MariaDB","type":"->","args":["_metadata","users"]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/database\/src\/Database\/Database.php","line":391,"function":"getDocument","class":"Utopia\\Database\\Database","type":"->","args":[{"$id":"_metadata","$collection":"_metadata","name":"collections","attributes":[{"$id":"name","key":"name","type":"string","size":256,"required":true,"signed":true,"array":false,"filters":[]},{"$id":"attributes","key":"attributes","type":"string","size":1000000,"required":false,"signed":true,"array":false,"filters":["json"]},{"$id":"indexes","key":"indexes","type":"string","size":1000000,"required":false,"signed":true,"array":false,"filters":["json"]}],"indexes":[]},"users"]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/database\/src\/Database\/Database.php","line":1049,"function":"getCollection","class":"Utopia\\Database\\Database","type":"->","args":["users"]},{"file":"\/usr\/src\/code\/app\/init.php","line":790,"function":"getDocument","class":"Utopia\\Database\\Database","type":"->","args":["users",""]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":350,"function":"{closure}","args":["default",{"teamInternalId":"2","teamId":"62c2ee2e79937ccf44ae","name":"ce-non-existing-words","description":"","logo":"","url":"","version":"0.15.1","legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","services":[],"auths":{"limit":0,"emailPassword":true,"usersAuthMagicURL":true,"anonymous":true,"invites":true,"JWT":true,"phone":true},"authProviders":[],"platforms":[],"webhooks":[],"keys":[],"domains":[],"search":"62c2ee42808d3aafca9c ce-non-existing-words","$read":["team:62c2ee2e79937ccf44ae"],"$write":["team:62c2ee2e79937ccf44ae\/developer","team:62c2ee2e79937ccf44ae\/owner"],"$id":"62c2ee42808d3aafca9c","$internalId":"2","$createdAt":1656942146,"$updatedAt":1656942146,"$collection":"projects"},{"$id":"console","$internalId":"console","name":"Appwrite","$collection":"projects","description":"Appwrite core engine","logo":"","teamId":-1,"webhooks":[],"keys":[],"platforms":[{"$collection":"platforms","name":"Localhost","type":"web","hostname":"localhost"}],"legalName":"","legalCountry":"","legalState":"","legalCity":"","legalAddress":"","legalTaxId":"","auths":{"limit":1},"authWhitelistEmails":[],"authWhitelistIPs":[]},{},{},{},{}]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":369,"function":"getResource","class":"Utopia\\App","type":"->","args":["user"]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":560,"function":"getResources","class":"Utopia\\App","type":"->","args":[["utopia","request","response","console","project","dbForConsole","user","locale","clients"]]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":694,"function":"execute","class":"Utopia\\App","type":"->","args":[{},{}]},{"file":"\/usr\/src\/code\/app\/http.php","line":257,"function":"run","class":"Utopia\\App","type":"->","args":[{},{}]}],"version":"0.15.1"}
```

![image](https://user-images.githubusercontent.com/17837758/177169526-c85579b7-1c4e-4ee5-9929-50a38d8da3a0.png)

### 🎲 Appwrite version

Version 0.15.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use Traefik reverse proxy

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Some are pretty critical, like the appwrite-worker-database.

**Comment by khashashin** [comment]
I've updated my docker-compose as it shown in docs and all services are running. But I still get the error in the Browser-Console:

![image](https://user-images.githubusercontent.com/17837758/177222989-dbc5ee21-bc65-457c-af40-d9332cea1e50.png)

```
AppwriteException: {"message":"Error: Table 'appwrite_db._2__metadata' doesn't exist","code":500,"file":"@swoole-src\/library\/core\/Database\/PDOStatementProxy.php","line":64,"trace":[{"file":"\/usr\/src\/code\/vendor\/utopia-php\/database\/src\/Database\/Adapter\/MariaDB.php","line":431,"function":"__call","class":"Swoole\\Database\\PDOStatementProxy","type":"->","args":["execute",[]]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/database\/src\/Database\/Database.php","line":1065,"function":"getDocument","class":"Utopia\\Database\\Adapter\\MariaDB","type":"->","args":["_metadata","stats"]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/database\/src\/Database\/Database.php","line":391,"function":"getDocument","class":"Utopia\\Database\\Database","type":"->","args":[{"$id":"_metadata","$collection":"_metadata","name":"collections","attributes":[{"$id":"name","key":"name","type":"string","size":256,"required":true,"signed":true,"array":false,"filters":[]},{"$id":"attributes","key":"attributes","type":"string","size":1000000,"required":false,"signed":true,"array":false,"filters":["json"]},{"$id":"indexes","key":"indexes","type":"string","size":1000000,"required":false,"signed":true,"array":false,"filters":["json"]}],"indexes":[]},"stats"]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/database\/src\/Database\/Database.php","line":1249,"function":"getCollection","class":"Utopia\\Database\\Database","type":"->","args":["stats"]},{"file":"\/usr\/src\/code\/app\/controllers\/api\/projects.php","line":296,"function":"find","class":"Utopia\\Database\\Database","type":"->","args":["stats",[{},{}],30,0,["time"],["DESC"]]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/database\/src\/Database\/Validator\/Authorization.php","line":161,"function":"{closure}","args":[]},{"file":"\/usr\/src\/code\/app\/controllers\/api\/projects.php","line":322,"function":"skip","class":"Utopia\\Database\\Validator\\Authorization","type":"::","args":[{}]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":593,"function":"{closure}","args":["62c2ee42808d3aafca9c","30d",{},{},{},{}]},{"file":"\/usr\/src\/code\/vendor\/utopia-php\/framework\/src\/App.php","line":694,"function":"execute","class":"Utopia\\App","type":"->","args":[{},{}]},{"file":"\/usr\/src\/code\/app\/http.php","line":257,"function":"run","class":"Utopia\\App","type":"->","args":[{},{}]}],"version":"0.15.1"}
```

**Comment by khashashin** [comment]
New docker-compose file:

```
version: '3'

services:
  appwrite:
    image: appwrite/appwrite:0.15.1
    container_name: appwrite
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.appwrite.loadBalancer.server.port=80"
      - "traefik.http.routers.appwrite.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.appwrite.entrypoints=web-secure"
      - "traefik.http.routers.appwrite.rule=Host(`fb.gibbit.ch`)"
    env_file: .env
    #entrypoint:
    #  - install
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-functions:/storage/functions:rw
    depends_on:
      - redis
      - mariadb
      - influxdb
    networks:
      - appwrite
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-realtime:
    image: appwrite/appwrite:0.15.1
    entrypoint: realtime
    container_name: appwrite-realtime
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
        #- "traefik.constraint-label-stack=appwrite"
        #- "traefik.docker.network=appwrite"
      - "traefik.http.services.appwrite_realtime.loadBalancer.server.port=80"
      #ws
      #- "traefik.http.routers.appwrite_realtime_ws.entrypoints=web"
      #- "traefik.http.routers.appwrite_realtime_ws.rule=(Host(`fb.gibbit.ch`) && PathPrefix(`/v1/realtime`))"
      #- "traefik.http.routers.appwrite_realtime_ws.service=appwrite_realtime"
      - "traefik.http.routers.appwrite_realtime.entrypoints=web-secure"
      - "traefik.http.routers.appwrite_realtime.rule=(Host(`fb.gibbit.ch`) && PathPrefix(`/v1/realtime`))"
      - "traefik.http.routers.appwrite_realtime.tls.certresolver=letsEncrypt"
        #- "traefik.http.routers.appwrite_realtime.service=appwrite_realtime"
        #- "traefik.http.routers.appwrite_realtime_wss.tls=true"
    networks:
      - appwrite
    depends_on:
      - mariadb
      - redis
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-audits:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-audits
    container_name: appwrite-worker-audits
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
      - mariadb
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-webhooks:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-webhooks
    container_name: appwrite-worker-webhooks
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
      - mariadb
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-deletes:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-deletes
    container_name: appwrite-worker-deletes
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
      - mariadb
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-builds:/storage/builds:rw
      - appwrite-certificates:/storage/certificates:rw
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'


  appwrite-worker-databases:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-databases
    container_name: appwrite-worker-databases
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
      - mariadb
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-builds:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-builds
    container_name: appwrite-worker-builds
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
      - mariadb
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-certificates:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-certificates
    container_name: appwrite-worker-certificates
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
      - mariadb
    volumes:
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-functions:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-functions
    container_name: appwrite-worker-functions
    restart: unless-stopped
    networks:
      - appwrite
    #link:
        #- appwrite-executor
    depends_on:
      - redis
      - mariadb
      - appwrite-executor
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-executor:
    image: appwrite/appwrite:0.15.1
    entrypoint: executor
    container_name: appwrite-executor
    restart: unless-stopped
    stop_signal: SIGINT
    networks:
      appwrite:
      runtimes:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-functions:/storage/functions:rw
      - appwrite-builds:/storage/builds:rw
      - /tmp:/tmp:rw
    depends_on:
      - redis
      - mariadb
      - appwrite
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-mails:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-mails
    container_name: appwrite-worker-mails
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-worker-messaging:
    image: appwrite/appwrite:0.15.1
    entrypoint: worker-messaging
    container_name: appwrite-worker-messaging
    networks:
      - appwrite
    depends_on:
      - redis
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-maintenance:
    image: appwrite/appwrite:0.15.1
    entrypoint: maintenance
    container_name: appwrite-maintenance
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-usage:
    image: appwrite/appwrite:0.15.1
    entrypoint: usage
    container_name: appwrite-usage
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - influxdb
      - mariadb
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  appwrite-schedule:
    image: appwrite/appwrite:0.15.1
    entrypoint: schedule
    container_name: appwrite-schedule
    restart: unless-stopped
    networks:
      - appwrite
    depends_on:
      - redis
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'


  redis:
    image: redis:6.2-alpine
    container_name: appwrite-redis
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory            512mb
      --maxmemory-policy     allkeys-lru
      --maxmemory-samples    5
    networks:
      - appwrite
    volumes:
      - appwrite-redis:/data:rw
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  mariadb:
    image: mariadb:10.7
    container_name: appwrite-mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
      - MYSQL_USER=${_APP_DB_USER}
      - MYSQL_DATABASE=${_APP_DB_SCHEMA}
      - MYSQL_PASSWORD=${_APP_DB_PASS}
    networks:
      - appwrite
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    command: 'mysqld --innodb-flush-method=fsync'
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  influxdb:
    image: appwrite/influxdb:1.5.0
    container_name: appwrite-influxdb
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-influxdb:/var/lib/influxdb:rw
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

  telegraf:
    image: appwrite/telegraf:1.4.0
    container_name: appwrite-telegraf
    restart: unless-stopped
    networks:
      - appwrite
    env_file: .env
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

networks:
  gateway:
  appwrite:
    external: true
  runtimes:

volumes:
  appwrite-mariadb:
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
  appwrite-certificates:
  appwrite-functions:
  appwrite-builds:
  appwrite-influxdb:
  appwrite-config:
  appwrite-executor:
```
