### ISSUE TITLE
Cannot install AppWrite (appwrite.io IP is blocked in Russia)

### ISSUE THREAD

**Issue by ikarelin** [appwrite/appwrite#374]
$ sudo docker run -it --rm     --volume /var/run/docker.sock:/var/run/docker.sock     --volume "$(pwd)"/appwrite:/install/appwrite:rw     -e version=0.6.2     appwrite/install
Starting Appwrite installation...
Choose your server hostname: (default: 'localhost')

Choose your server HTTP port: (default: 80)

Choose your server HTTPS port: (default: 443)

Choose a CNAME target for your custom domains: (default: 'localhost')

Failed to fetch Docker Compose file

**Comment by eldadfux** [comment]
What OS are you using?

**Comment by ikarelin** [comment]
I've tried on Debian 10 and Zorin OS 15.2 (which is based on Ubuntu 18.04) with the same result.

**Comment by eldadfux** [comment]
Can you access the docker-compose file manually from this hosts?
https://appwrite.io/docker-compose.yml

**Comment by eldadfux** [comment]
And if you could check your docker CLI version, that might be helpful...

**Comment by ikarelin** [comment]
No, I cannot access the file (tried with wget).
The site is https://appwrite <https://appwrite/>.io  is  working in browser on the same machine.

Maybe the problem is that I’m using http proxy in my network, so it can open the site but cannot download docker file.

Tried on ubuntu 18, the same result.

**Comment by eldadfux** [comment]
Can you tell if the site returns any status code error?

**Comment by ikarelin** [comment]
https://appwrite.io is not opening from Russia (even the main site).
That’s why I’m using my proxy located in UK.
So proxy opening the main site, but cannot download the docker stuff.
Maybe I need to open some additional ports on proxy for this.

But when I’m trying to wget https://appwrite.io/docker-compose.yml <https://appwrite.io/docker-compose.yml>, the wget command just freezes and the port must to be 443, which is opened …
Hmmm...

**Comment by eldadfux** [comment]
Any idea how we can check why it's blocked?

![image](https://user-images.githubusercontent.com/1297371/83684310-7fe98a80-a5ef-11ea-9ea3-5e0fccb1bdc9.png)

**Comment by ikarelin** [comment]
It’s blocked by decision of General prosecutor's office of Russia.
You can search on their site by decision number.

I think you’ll need to find a Russian speaking guy to do this for you ))

**Comment by eldadfux** [comment]
I will try to check this with our hosting provider, maybe we can also switch IP address for the website.  Anyway you can try and install Appwrite manually by downloading the content of:
https://appwrite.io/docker-compose.yml, save it as `docker-compose.yml` and run:

```
docker-compose up -d
```

You can also customise the setup by editing the env vars in the `docker-compose.yml`, you can check more about this here: https://github.com/appwrite/appwrite/blob/master/docs/tutorials/environment-variables.md

**Comment by ikarelin** [comment]
Actually I want to install it on my local server to test.
I’m a Flutter developer and now I’m using Firebase to my production projects.

As I can see, Appwrite can almost replace it except the verification by phone and SMS messaging/push notifications.
But there is a lot of providers of this services.

So I want to give an Appwrite a try in one of my test projects. 

Thank you for help and best regards.

**Comment by eldadfux** [comment]
I'm adding a copy of the Appwrite docker-compose.yml file, in case more users from Russia are having troubles accessing appwrite.io and don't have access to any VPN service:
```yml
version: '3'

services:
    traefik:
        image: traefik:v2.1.4
        command:
            - --providers.file.directory=/storage/config
            - --providers.file.watch=true
            - --providers.docker=true
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - appwrite-config:/storage/config:ro
            - appwrite-certificates:/storage/certificates:ro
        depends_on:
            - appwrite
        networks:
            - gateway
            - appwrite
    
    appwrite:
        image: appwrite/appwrite:latest
        restart: unless-stopped
        networks:
            - appwrite
        labels:
            - traefik.http.routers.appwrite.rule=PathPrefix(`/`)
            - traefik.http.routers.appwrite-secure.rule=PathPrefix(`/`)
            - traefik.http.routers.appwrite-secure.tls=true
        volumes:
            - appwrite-uploads:/storage/uploads:rw
            - appwrite-cache:/storage/cache:rw
            - appwrite-config:/storage/config:rw
            - appwrite-certificates:/storage/certificates:rw
        depends_on:
            - mariadb
            - redis
            - smtp
            - clamav
            - influxdb
            - telegraf
        environment:
            - _APP_ENV=production
            - _APP_OPENSSL_KEY_V1=your-secret-key
            - _APP_DOMAIN=localhost
            - _APP_DOMAIN_TARGET=localhost
            - _APP_REDIS_HOST=redis
            - _APP_REDIS_PORT=6379
            - _APP_DB_HOST=mariadb
            - _APP_DB_PORT=3306
            - _APP_DB_SCHEMA=appwrite
            - _APP_DB_USER=user
            - _APP_DB_PASS=password
            - _APP_INFLUXDB_HOST=influxdb
            - _APP_INFLUXDB_PORT=8086
            - _APP_STATSD_HOST=telegraf
            - _APP_STATSD_PORT=8125
            - _APP_SMTP_HOST=smtp
            - _APP_SMTP_PORT=25

    mariadb:
        image: appwrite/mariadb:1.0.3
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-mariadb:/var/lib/mysql:rw
        environment:
            - MYSQL_ROOT_PASSWORD=rootsecretpassword
            - MYSQL_DATABASE=appwrite
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        command: 'mysqld --innodb-flush-method=fsync'

    smtp:
        image: appwrite/smtp:1.0.1
        restart: unless-stopped
        networks:
            - appwrite
        environment:
            - MAILNAME=appwrite
            - RELAY_NETWORKS=:192.168.0.0/24:10.0.0.0/16

    redis:
        image: redis:5.0
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-redis:/data:rw

    clamav:
        image: appwrite/clamav:1.0.8
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-uploads:/storage/uploads

    influxdb:
        image: influxdb:1.6
        restart: unless-stopped
        networks:
            - appwrite
        volumes:
            - appwrite-influxdb:/var/lib/influxdb:rw

    telegraf:
        image: appwrite/telegraf:1.0.0
        restart: unless-stopped
        networks:
            - appwrite

networks:
    gateway:
    appwrite:

volumes:
    appwrite-mariadb:
    appwrite-redis:
    appwrite-cache:
    appwrite-uploads:
    appwrite-certificates:
    appwrite-influxdb:
    appwrite-config:
```
