### ISSUE TITLE
🐛 Bug Report: CORS error after replacing traefik with nginx

### ISSUE THREAD

**Issue by SomeBody16** [appwrite/appwrite#4622]
### 👟 Reproduction steps

1. Default installation on VPS
2. Remove traefik service and restart
3. Login, create project
4. Register Web App -> hostname: `localhost` (Or `*`, `your-real-domain`, anything that should work)

5. Create another docker-compose.nginx.yml :
```yml
version: '3'

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: youremail@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    networks:
      - appwrite_appwrite

networks:
  appwrite_appwrite:
    external: true

volumes:
  nginx_secrets:
```

6. Create nginx_secrets/your-domain.com.conf :
```conf
server {
    # Listen to port 443 on both IPv4 and IPv6.
    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    # Domain names this server should respond to.
    server_name your-domain.com;

    # Load the certificate files.
    ssl_certificate         /etc/letsencrypt/live/your-domain.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/your-domain.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/your-domain.com/chain.pem;

    # Load the Diffie-Hellman parameter.
    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_pass http://appwrite;
    }

    location /realtime {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_pass http://appwrite-realtime;
        proxy_http_version 1.1;
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }
}
```

7. Run `docker compose -f ./docker-compose.nginx.yml up`
8. Create any app on remote machine
9. Connect to this machine with VSCode Remote SSH
10. Forward port with VSCode (example 3000 -> 3000)
11. Run this app and make request ([example app](https://stackblitz.com/edit/nextjs-fkftn2?file=pages/index.js))
In my case app is using appwrite endpoint directly to nginx service, not localhost so it's not going through VSCode. Just browser -> nginx -> appwrite

### 👍 Expected behavior

It should work and return proper response, for `localhost`, `*` and any working domain 

### 👎 Actual Behavior

```
Access to XMLHttpRequest at 'https://your-domain.com/account' 
from origin 'http://localhost:4200' 
has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Idk on which step is failing (Browser -> nginx -> appwrite)

### 🎲 Appwrite version

Version 1.0.3.501

### 💻 Operating system

Linux

### 🧱 Your Environment

`lsb_release -a`
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

`docker -v`
```
Docker version 20.10.20, build 9fdeb9c
```

`code -v`
```
1.72.2
d045a5eda657f4d7b676dedbfa7aab8207f8a075
x64
```

Host OS: Windows 10 (I'm connecting to VPS with Ubuntu with VSCode)
VPS provider: [webh.pl](webh.pl)
Domain provider: [https://domains.google.com](https://domains.google.com)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)
