### ISSUE TITLE
🐛 Bug Report: Session object store incorrect info

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#4893]
### 👟 Reproduction steps

Session showing me my host server IP and Location instead of logged in user.

![Screenshot 2022-12-21 193413](https://user-images.githubusercontent.com/18592683/208931389-88f60f39-5554-4003-ab26-71dba57fca5b.png)

### 👍 Expected behavior

Session should show logged in user IP and Location.

### 👎 Actual Behavior

Session showing me my server IP and Location instead of logged in user.

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@usamashafiqs thanks for raising this issue! 🙏🏼 Do you have a reverse proxy in front of Appwrite?

**Comment by stnguyen90** [comment]
> But appwrite already have traefik as reverse proxy.

Traefik should be fine and shouldn't interfere with the IP address that is collected. 

Do you have anything else running on the server? Do you have anything else in front of Appwrite? Any other information you can provide about your infrastructure/architecture?

**Comment by usamashafiqs** [comment]
Only appwrite instance is running on server.
=> Ubuntu 22.04.1 LTS
=> Docker
=> Appwrite

![Screenshot 2022-12-22 at 10 56 57 PM](https://user-images.githubusercontent.com/18592683/209197453-1f3b2de9-f705-4c91-a4ee-b612828efd0f.png)

**Comment by stnguyen90** [comment]
The problem could be Cloudflare proxy. Since the request some from Cloudflare proxy, Appwrite uses that as the source IP address. In order to get Appwrite to use the IP address before Cloudflare, you'll have to tell Appwrite to trust Cloudflare and use the IP passed in the header using the [forwardedHeaders](https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers) option.

I would recommend creating a `docker-compose.override.yml` file in the same folder as your Appwrite `docker-compose.yml` file if you haven't already and adding this:

```yaml
services:
  traefik:
    command:
      - --providers.file.directory=/storage/config
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`,`appwrite`)
      - --entrypoints.appwrite_web.address=:80
      - --entrypoints.appwrite_websecure.address=:443
      - --entrypoints.appwrite_web.forwardedHeaders.trustedIPs=<IP Address of Cloudflare>
      - --entrypoints.appwrite_websecure.forwardedHeaders.trustedIPs=<IP Address of Cloudflare>
```

The list of Cloudflare IP Addresses can be found [here](https://www.cloudflare.com/ips/).

After creating this file, run `docker compose up -d` to apply the changes.

Alternatively, you can trust all IPs by putting this instead of the `trustedIPs`:

```yaml
      - --entrypoints.appwrite_web.forwardedHeaders.insecure
      - --entrypoints.appwrite_websecure.forwardedHeaders.insecure
```
