### ISSUE TITLE
🐛 Bug Report: deleted project still exists in appwrite

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/appwrite#4930]
### 👟 Reproduction steps

Deleted project not showing in appwrite console but showing during migration.

I migrated to v1.2.0 after migration it showing me 8 projects are migrated but only have 4 project in appwrite console.

![Screenshot 2022-12-28 225857](https://user-images.githubusercontent.com/18592683/209853814-31f5203a-9559-4ac3-bb7a-89930a91f463.png)

I deleted these projects a mouth ago.
It showing me all of my deleted project during migration.

![image](https://user-images.githubusercontent.com/18592683/209853687-5e8c30a0-9ba8-4fc0-b21e-1b5a45465387.png)

### 👍 Expected behavior

Delete project should delete completely form appwrite.

### 👎 Actual Behavior

Deleted project not showing in appwrite console but showing during migration.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@usamashafiqs thanks for raising this issue! 🙏🏼 Do you happen to remember what version you were on when you deleted the projects?

**Comment by usamashafiqs** [comment]
@stnguyen90 can't remember the exact date of deletion 1 to 2 mouths ago.

**Comment by suleimanas** [comment]
@stnguyen90  I can confirm this issue on version 1.1.2

**Comment by suleimanas** [comment]
And version 1.2.0 all the project's tables and data remains after delete

**Comment by suleimanas** [comment]
@usamashafiqs yes a quick way is to use **phpmyadmin**

https://hub.docker.com/_/phpmyadmin

in my `docker-compose.override.yml`
```
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 999999999
    depends_on:
      - mariadb
    networks:
      - appwrite
```
