### ISSUE TITLE
📚 Documentation on how to prevent data loss after docker service stop

### ISSUE THREAD

**Issue by YousefAlsbaihi** [appwrite/appwrite#5042]
### **This post is a solution, Not an issue**

The issue is that whenever the docker service stops, it cause the data to be lost and cannot be retrieved back unless you have a backup.

The reason for this is because docker storing the data into the image, and whenever you restart/shutdown the service, it will remove/delete all it's data content and the drive. 

To solve this you need to create external drive for the data you don't want to be lost.

in my case i needed the storage and the database

to do so without losing your data what you need to do is keep your docker running and create 2 files `backup.sh` and `restore.sh`

**DON'T STOP YOUR DOCKER**

in the `backup.sh` you need to put this code below

```
#!/bin/bash

mkdir -p backup

docker compose exec mariadb sh -c 'exec mysqldump --all-databases --add-drop-database -u"$MYSQL_USER" -p"$MYSQL_PASSWORD"' > ./backup/dump.sql

appwrite_volumes=(uploads cache config certificates functions)
for volume in ${appwrite_volumes[@]}; do
    mkdir -p backup && docker run --rm --volumes-from "$(docker compose ps -q appwrite)" -v $PWD/backup:/backup ubuntu bash -c "cd /storage/$volume && tar cvf /backup/$volume.tar ."
done

```
in the `restore.sh` you need to put this code below

```
#!/bin/bash

docker compose exec -T mariadb sh -c 'exec mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD"' < ./backup/dump.sql

appwrite_volumes=(uploads cache config certificates functions)
for volume in ${appwrite_volumes[@]}; do
    docker run --rm --volumes-from "$(docker compose ps -q appwrite)" -v $PWD/backup:/restore ubuntu bash -c "cd /storage/$volume && tar xvf /restore/$volume.tar --strip 1"
done
```

Next you need to give execution permission for both files

```
chmod +x restore.sh
chmod +x backup.sh
```

Now you you need to run `backup.sh` files to make a backup do so run this command

`./backup.sh` 

once it's done, take down docker by running 

`docker-compose down -v`

once it's down, go to `docker-compose.yml` and run 

`nano docker-compose.yml`

now you need to add the external drive and it's location. 

go all the way down to `volumes` in your `docker-compose.yml` file and under `appwrite-mariadb:` add `external: true`
and `appwrite-uploads:` add `external: true`, it should look something like this 

```
volumes:
  appwrite-mariadb:
    external: true
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
    external: true
  appwrite-certificates:
  appwrite-functions:
  appwrite-builds:
  appwrite-influxdb:
  appwrite-config:
  appwrite-executor:
```

now we have them in external volumes, we need to specify where it's locate.
do to the `mariadb` service and on `volumes:` add a path in front of it to look like this 

```
  mariadb:
    image: mariadb:10.7 # fix issues when upgrading using: mysql_upgrade -u root -p
    container_name: appwrite-mariadb
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - .docker/appwrite-mariadb:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
      - MYSQL_DATABASE=${_APP_DB_SCHEMA}
      - MYSQL_USER=${_APP_DB_USER}
      - MYSQL_PASSWORD=${_APP_DB_PASS}
    command: 'mysqld --innodb-flush-method=fsync'

```
in my case i added a folder called `.docker` 
now create this folder in the same directory as the `docker-compose.yml`

and on the `appwrite` service add same folder name in front of `appwrite-uploads:/storage/uploads:rw` in `volumes`
do the same thing on `appwrite-worker-deletes`

save your docker and start it by using 

`docker compose up -d`

once it's started it will start empty blank app
run the restore script by running the command 

`./restore.sh`

once it's restored, you are all set.

you can test it by stopping the service and take it back up and you will see no data loss 
if you also looked inside .docker file we created, you will see all your files are in there so they won't be removed/deleted when the service stops 

Hope this helps

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)
