### ISSUE TITLE
🐛 Bug Report: Increase Pagination maximum offset from 5000

### ISSUE THREAD

**Issue by anhmeorv99** [appwrite/appwrite#5506]
### 👟 Reproduction steps

Pagination: The maximum offset is 5000. But in some cases, i want use offset > 5000 . I want have default max offset = 5000 and i can config max offset from ENV.

### 👍 Expected behavior

Pagination: The maximum offset is 5000. But in some cases, i want use offset > 5000 . I want have default max offset = 5000 and i can config max offset from ENV.

### 👎 Actual Behavior

Pagination: The maximum offset is 5000. But in some cases, i want use offset > 5000 . I want have default max offset = 5000 and i can config max offset from ENV.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by deepam-kapur** [comment]
Raised PR - https://github.com/appwrite/appwrite/pull/5508
On branch - deepam-kapur:fix-5506-pr-for-limit-document-count

Please review it! & lemme know if any change is required!

**Comment by joeyouss** [comment]
Hi, there is a reason for this.
The maximum offset is 5000, since the request gets slower as the number of records increases because the database has to read up to the offset number of rows to know where it should start selecting data. Also when there is data added in high frequency - the individual pages might skip results.

**Comment by byawitz** [comment]
In case you have a need to remove this limit in a self-hosted Appwrite, you can do so by overriding `init.php` file, like so:
1. Edit your `docker-compose.yml` file, and bind the file to any container that uses the `appwrite/appwrite` image.
```yaml
   appwrite:
    image: appwrite/appwrite:1.3.7
    container_name: appwrite
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    labels:
      ...
    volumes:
      ...
      - /root/customized/init.php:/usr/src/code/src/app/init.php
    depends_on:
      ...
    environment:
      ...
```
2. Create a file in the location `/root/customized` and name it `init.php`. inside that file paste all the content of the original [init.php](https://github.com/appwrite/appwrite/blob/master/app/init.php) file 
3. Edit this [line](https://github.com/appwrite/appwrite/blob/master/app/init.php#L87). set it to whatever value you like.
```php
const APP_LIMIT_COUNT = 5000000;
```
Then you're set to go.
