### ISSUE TITLE
Can't sign up

### ISSUE THREAD

**Issue by jsaberon** [appwrite/appwrite#6]
When I'm try to create an account it throws me an JSON responds

{"message":"SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known","code":2002,"file":"\/usr\/share\/nginx\/html\/app\/init.php","line":68,"trace":[{"file":"\/usr\/share\/nginx\/html\/app\/init.php","line":68,"function":"__construct","class":"PDO","type":"->","args":["mysql:host=mariadb;dbname=appwrite;charset=utf8mb4","root","password",{"1002":"SET NAMES utf8mb4","2":5}]},{"file":"\/usr\/share\/nginx\/html\/vendor\/utopia-php\/registry\/src\/Registry\/Registry.php","line":72,"function":"{closure}","args":[]},{"file":"\/usr\/share\/nginx\/html\/app\/app.php","line":196,"function":"get","class":"Utopia\\Registry\\Registry","type":"->","args":["db"]},{"function":"{closure}","args":[]},{"file":"\/usr\/share\/nginx\/html\/vendor\/utopia-php\/abuse\/src\/Abuse\/Adapters\/TimeLimit.php","line":263,"function":"call_user_func","args":[{}]},{"file":"\/usr\/share\/nginx\/html\/vendor\/utopia-php\/abuse\/src\/Abuse\/Adapters\/TimeLimit.php","line":159,"function":"getPDO","class":"Utopia\\Abuse\\Adapters\\TimeLimit","type":"->","args":[]},{"file":"\/usr\/share\/nginx\/html\/vendor\/utopia-php\/abuse\/src\/Abuse\/Adapters\/TimeLimit.php","line":233,"function":"count","class":"Utopia\\Abuse\\Adapters\\TimeLimit","type":"->","args":["url:localhost\/v1\/auth\/register,ip:172.18.0.1",1567558800]},{"file":"\/usr\/share\/nginx\/html\/app\/app.php","line":216,"function":"remaining","class":"Utopia\\Abuse\\Adapters\\TimeLimit","type":"->","args":[]},{"function":"{closure}","args":[]},{"file":"\/usr\/share\/nginx\/html\/vendor\/utopia-php\/framework\/src\/App.php","line":387,"function":"call_user_func_array","args":[{},[]]},{"file":"\/usr\/share\/nginx\/html\/app\/app.php","line":793,"function":"run","class":"Utopia\\App","type":"->","args":[{},{}]},{"file":"\/usr\/share\/nginx\/html\/public\/index.php","line":27,"args":["\/usr\/share\/nginx\/html\/app\/app.php"],"function":"include"}],"version":"latest"}

**Comment by eldadfux** [comment]
Hi this seems like your Appwrite instance is having trouble connecting with the MariaDB container.

To try and debug what failed, more information is needed:

1. Whats is your docker version?

2. Check your containers status using 'docker ps' command and paste it here.

3. If any of your Appwrite containers is down please paste the container log in here.

4. As this seems a database issue, please login into your mariadb container and check if you have the 'appwrite' database set up with all Appwrite tables. You can do so using the docker command: 'docker exec -it [container-id] bash', inside the container use: 'mysql -u root -p' and type your container password (default is: 'password'). In the mysql client check the output of: 'USE appwrite; SHOW FULL TABLES'.

**Comment by jsaberon** [comment]
Docker Version: Docker version 19.03.1, build 74b1e89

**docker ps**
```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                          PORTS                NAMES
deb86f443cf3        appwrite/appwrite        "/bin/bash /entrypoi…"   6 hours ago         Up 13 minutes                   0.0.0.0:80->80/tcp   appwrite-ce_appwrite_1
aa3146af56d7        appwrite/clamav:1.0.4    "/bin/bash /entrypoi…"   6 hours ago         Up 13 minutes (healthy)         3310/tcp             appwrite-ce_clamav_1
77f8e22f604c        appwrite/mariadb:1.0.0   "docker-entrypoint.s…"   6 hours ago         Restarting (1) 19 seconds ago                        appwrite-ce_mariadb_1
a7ef4b6ad927        redis:5.0                "docker-entrypoint.s…"   29 hours ago        Up 13 minutes                   6379/tcp             appwrite-ce_redis_1
```

I'm using Windows and I cant read the logs. because it is encrypted.

Please comment if you need more information

**Comment by eldadfux** [comment]
From the logs you posted its seems your mariadb container has trouble starting ('Restarting (1) 19 seconds ago').

The only way to debug this is to get the mariadb logs, don't really know why you are having trouble to get them. Do you have any error message?

A way to try and bypass the problem is to delete your storage directory, your appwrite/mariadb container and image and run the 'docker-compose up -d' command in the appwrite-ce working directory.

Another issue is that in your logs you posted only 4 containers, please make sure all the containers listed in the docker-compose.yml file are up and running.

**Comment by jsaberon** [comment]
I change my maria db container port 3306:3306 to 3306:5000 and I encountered the same error

This is the new **docker ps**:
```
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS                   PORTS                                        NAMES
5d02775f5863        appwrite/appwrite         "/bin/bash /entrypoi…"   26 seconds ago      Up 23 seconds            0.0.0.0:80->80/tcp                           appwrite-ce_appwrite_1
1147ca8f2f61        appwrite/mariadb:1.0.0    "docker-entrypoint.s…"   38 seconds ago      Up Less than a second    3306/tcp, 0.0.0.0:3306->5000/tcp             appwrite-ce_mariadb_1
89aba917429c        appwrite/clamav:1.0.4     "/bin/bash /entrypoi…"   2 minutes ago       Up 2 minutes (healthy)   3310/tcp                                     appwrite-ce_clamav_1
2ee66d3c432b        influxdb:1.6              "/entrypoint.sh infl…"   2 minutes ago       Up 2 minutes             0.0.0.0:8086->8086/tcp                       appwrite-ce_influxdb_1
7c4125248f91        appwrite/telegraf:1.0.0   "/entrypoint.sh tele…"   2 days ago          Up 2 minutes             8092/udp, 8094/tcp, 0.0.0.0:8125->8125/udp   appwrite-ce_telegraf_1
a7ef4b6ad927        redis:5.0                 "docker-entrypoint.s…"   2 days ago          Up 4 minutes             6379/tcp                                     appwrite-ce_redis_1
174b7bb663cc        appwrite/smtp:1.0.0       "/bin/entrypoint.sh …"   2 days ago          Up 2 minutes             0.0.0.0:25->25/tcp                           appwrite-ce_smtp_1

```

**Comment by eldadfux** [comment]
When changing mariadb port number make sure to let the 'appwrite' container know about the new port with the '_APP_DB_PORT' env variable.

it should look like this:

```yml
version: "3"

services:
    appwrite:
        image: appwrite/appwrite
        restart: unless-stopped
        volumes:
        - ./storage:/storage:rw
        ports:
        - "80:80"
        depends_on:
        - mariadb
        - redis
        - smtp
        - clamav
        - influxdb
        - telegraf
        environment:
        - _APP_ENV=development
        - _APP_OPENSSL_KEY_V1=your-secret-key
        - _APP_REDIS_HOST=redis
        - _APP_REDIS_PORT=6379
        - _APP_DB_HOST=mariadb
        - _APP_DB_PORT=5000
        - _APP_DB_SCHEMA=appwrite
        - _APP_DB_USER=root
        - _APP_DB_PASS=password
        - _APP_INFLUXDB_HOST=influxdb
        - _APP_INFLUXDB_PORT=8086
        - _APP_STATSD_HOST=telegraf
        - _APP_STATSD_PORT=8125

    mariadb:
        image: appwrite/mariadb:1.0.0
        restart: unless-stopped
        environment:
        - MYSQL_ROOT_PASSWORD=password
        volumes:
        - ./storage/db:/var/lib/mysql:rw
        ports:
        - 5000:3306/tcp

    smtp:
        image: appwrite/smtp:1.0.0
        environment:
        - MAILNAME=appwrite
        - RELAY_NETWORKS=:192.168.0.0/24:10.0.0.0/16
        ports:
        - "25:25"

    clamav:
        image: appwrite/clamav:1.0.4
        restart: unless-stopped
        volumes:
        - ./storage:/storage:rw
        
    redis:
        image: redis:5.0
        restart: unless-stopped

    influxdb:
        image: influxdb:1.6
        volumes:
        - ./storage/influxdb:/var/lib/influxdb
        ports:
        - "8086:8086"

    telegraf:
        image: appwrite/telegraf:1.0.0
        ports:
        - "8125:8125/udp"
```

Another thing to make sure is that the port was really the problem. Did you get error from docker indicating the port is already taken? As I wrote before, the best way to debug a container that keeps restarting is to check for its logs like this: 

```bash
docker logs [mariadb-container-id]
```
