### ISSUE TITLE
🐛 Bug Report:  Two repeated volumes are evident for: appwrite-worker-builds

### ISSUE THREAD

**Issue by criihz** [appwrite/appwrite#6184]
### 👟 Reproduction steps

When loading the file, two repeated volumes are evident for: appwrite-worker-builds

### 👍 Expected behavior

``` yml

appwrite-worker-builds:
    image: appwrite/appwrite:1.4.2
    entrypoint: worker-builds
    <<: *x-logging
    container_name: appwrite-worker-builds
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-functions:/storage/functions:rw
      - appwrite-builds:/storage/builds:rw
    depends_on:
      - redis
      - mariadb
    environment:
      - _APP_ENV


```

### 👎 Actual Behavior

``` yml

appwrite-worker-builds:
    image: appwrite/appwrite:1.4.2
    entrypoint: worker-builds
    <<: *x-logging
    container_name: appwrite-worker-builds
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-functions:/storage/functions:rw
      - appwrite-builds:/storage/builds:rw
    depends_on:
      - redis
      - mariadb
    volumes:
      - appwrite-functions:/storage/functions:rw
      - appwrite-builds:/storage/builds:rw
    environment:
      - _APP_ENV

```

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)
