### ISSUE TITLE
Finetuning docker-compose.yml

### ISSUE THREAD

**Issue by b0r1sp** [appwrite/appwrite#767]
I'd propose to provide two seperate `docker-compose.yml` files: one for development purposes and the other one for production. I can help with that if needed. IMHO the `docker-compose.yml` for production should be as simple and as less opiniated as possible, e.g. no build instructions, optional use of `traefik`, ...

**Use of docker image**

Currently from the docs it's not clear if a local build of appwrite is required. I'd prefer to use an image from docker hub instead:

```
appwrite:
    image: appwrite/appwrite:0.6.2
    container_name: appwrite
    #build:
    #  context: .
    #  args:
    #    - TESTING=true
    #    - VERSION=dev
```

I'd need some documentation which volumes are essential for production and which are just mounted to make development easier:

```
volumes:
      - ./data/appwrite/uploads:/storage/uploads:rw
      - ./data/appwrite/cache:/storage/cache:rw
      - ./data/appwrite/config:/storage/config:rw
      - ./data/appwrite/certificates:/storage/certificates:rw

      # is the following really needed? what is inside the docker image on docker hub?
      - ./phpunit.xml:/usr/share/nginx/html/phpunit.xml
      - ./tests:/usr/share/nginx/html/tests
      - ./app:/usr/share/nginx/html/app
     # - ./vendor:/usr/share/nginx/html/vendor
      - ./docs:/usr/share/nginx/html/docs
      - ./public:/usr/share/nginx/html/public
      - ./src:/usr/share/nginx/html/src
```

**Make `traefik` optional**

I'm in the situation to run appwrite on a host which already runs an existing traefik proxy. I'd like to expose appwrite to the existing traefik with the following labels:

```
appwrite:
    image: appwrite/appwrite:0.6.2
    labels:
      - traefik.http.routers.appwrite.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite-secure.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite-secure.tls=true
      # new
      - 'traefik.appwrite.backend=appwrite.dev.domain.io'
      - 'traefik.appwrite.frontend.rule=Host:appwrite.dev.domain.io'
      - 'traefik.appwrite.frontend.redirect.entryPoint=https'
      - 'traefik.appwrite.frontend.entryPoints=http,https'
      - 'traefik.port=80'
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
    networks:
      - appwrite
      - proxy
```

**Expose web-interfaces only via traefik**

I'd suggest to route all http/s traffic via traefik. In production none of the containers should expose it's web-interface via port-mapping to the host machine, example:

```
maildev:
    image: djfarrelly/maildev
    container_name: appwrite_maildev
    restart: unless-stopped
    labels:
      - 'traefik.appwrite-maildev.backend=appwrite-maildev.dev.domain.io'
      - 'traefik.appwrite-maildev.frontend.rule=Host:appwrite-maildev.dev.domain.io'
      - 'traefik.appwrite-maildev.frontend.redirect.entryPoint=https'
      - 'traefik.appwrite-maildev.frontend.entryPoints=http,https'
      - 'traefik.port=8080'
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
    networks:
      - appwrite
      - proxy
```

Therefore internal services stay internal, which is better for security, e.g. for the database:

```
mariadb:
    image: appwrite/mariadb:1.0.3
    networks:
      - appwrite
    ....
```
