### ISSUE TITLE
🐛 Bug Report: 

### ISSUE THREAD

**Issue by Kuromory** [appwrite/appwrite#7989]
### 👟 Reproduction steps

When I want to create a new Webhook and use the IP Address of the webhook server it wont allow it...
I give the IP as follow:
http://192.168.1.16:24040/sync

### 👍 Expected behavior

I can create the webhook

### 👎 Actual Behavior

get following error:
appwrite                      | [Error] Timestamp: 2024-04-18T07:43:23+00:00
appwrite                      | [Error] Method: POST
appwrite                      | [Error] URL: /v1/projects/:projectId/webhooks
appwrite                      | [Error] Type: Utopia\Exception
appwrite                      | [Error] Message: Invalid `url` param: 1. Value must be a valid URL with following schemes (http, https)
appwrite                      | 2. Value must be a public domain
appwrite                      |
appwrite                      | [Error] File: /usr/src/code/vendor/utopia-php/framework/src/App.php
appwrite                      | [Error] Line: 774

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

just use the docker version of appwrite

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by golu360** [comment]
I would love to pick this up!

**Comment by guites** [comment]
This is more of a feature than a bug. The validation is done at app/controllers/api/projects.php :

```php
App::post('/v1/projects/:projectId/webhooks')
    ...
    ->param('url', '', fn ($request) => new Multiple([new URL(['http', 'https']), new PublicDomain()], Multiple::TYPE_STRING), 'Webhook URL.', false, ['request'])
```

the `new PublicDomain()` class is from utopia-php/domains:  https://github.com/utopia-php/domains/blob/650463d2a1525273eb03223c48da9fb1a768bbf7/src/Domains/Validator/PublicDomain.php#L42

The current implementation doesn't let us "allow" arbitrary ips/domains (see https://github.com/utopia-php/domains/blob/650463d2a1525273eb03223c48da9fb1a768bbf7/tests/Validator/PublicDomainTest.php#L48).

I can see a solution where we set "allowed webhook domains" via an environment variable, but not too sure how to implement it/if it would be an accepted solution

**Comment by guites** [comment]
btw on older appwrite versions (1.4.x) I used to set docker hostnames for webhook URLs in order not to expose my webhook servers to the internet (on self hosted), so maybe we could treat this as a regression/bug

**Comment by Kuromory** [comment]
@guites would you be so kind and give me an example? I only know of 'host.docker.internal' as docker host name and this only works on windows... So I might miss something?

**Comment by guites** [comment]
> [@guites](https://github.com/guites) would you be so kind and give me an example? I only know of 'host.docker.internal' as docker host name and this only works on windows... So I might miss something?

sorry i might have worded it incorrectly. I meant the following setup, using docker compose:

```yml
  # excerpt from docker-compose.yml
  appwrite:
    image: appwrite/appwrite:1.4.5
    container_name: appwrite
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
      # ... rest of docker-compose stuff
  appwrite-webhook-handler:
    container_name: appwrite-webhook-handler
    # .. rest of docker-compose stuff
    networks:
      - appwrite
  ```

And then I could setup my webhook using `http://appwrite-webhook-handler:3005/endpoint` as a valid URL.

This worked prior to 1.5.x. Won't work anymore on 1.7.x due to the imposed public URL validation
