### ISSUE TITLE
🐛 Bug Report: AppwriteException: relationship_value_invalid, Invalid relationship value. Must be either a document ID or a document, array given. (400)

### ISSUE THREAD

**Issue by FigueiredoStable** [appwrite/appwrite#8909]
### 👟 Reproduction steps

Create a collection with one or more attributes with relationship, them try update one field who dosen't have a relationship.

My collection attributes:

![Image](https://github.com/user-attachments/assets/1ddbc539-4c95-4f35-bfe8-5a668db69c09)

Relationship details:

![Image](https://github.com/user-attachments/assets/7e3b4103-3e0e-4179-a04b-400650257244)

Try to update one field without relationship:

``` dart
      try {
        Map data = {'serial': "12345"};
        await database.updateDocument(
          databaseId: "00000",
          collectionId: "11111",
          documentId: "222222",
          data: data,
        );
        return context.res.json({'status': false, 'message': 'Serial updated'}, 200);
      } catch (e) {
        return context.res.json({'status': false, 'message': 'Error to update serial', 'exception': e.toString()}, 500);
      }
```

This is a example, i have checked the documentId, collection and database collection id. 

### 👍 Expected behavior

Update only "serial" field.

On example code, i don't need, and not try to update "mobileDevices" relationship filed.

### 👎 Actual Behavior

```json
"responseBody": "{\"status\":false,\"message\":\"Error to update serial\",\"exception\":\"AppwriteException: relationship_value_invalid, Invalid relationship value. Must be either a document ID or a document, array given. (400)\"}",
```

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Self Hosted

```YAML
Operating system: Ubuntu Linux 24.04.1
Kernel and CPU: Linux 6.8.0-47-generic on x86_64
Processor information: Intel(R) N100, 4 cores 
System uptime: 3 days, 5 hours, 49 minutes
Running processes: 288 
CPU load averages: 0.21 (1 min) 0.22 (5 mins) 0.46 (15 mins)
Real memory: 2.6 GiB used / 3.19 GiB cached / 11.41 GiB total
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)
